import type { Metadata } from 'next'
import './globals.css'
import { Providers } from '@/components/Providers'
import { Bounce, ToastContainer } from 'react-toastify'

export const metadata: Metadata = {
  title: 'MetaNode Stake',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
          />
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  )
}
